version: '3.8'

services:
  backend:
    image: node:18
    container_name: node_backend_sgh
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    command: sh -c "npm install && node index.js"
    environment:
      DB_HOST: 192.168.1.83   # IP del servidor Ubuntu
      DB_PORT: 3306
      DB_USER: sghuser
      DB_PASSWORD: sghpassword
      DB_NAME: sgh_db